=== juniordrizzy/Projet-SGBD-Reverse-Engeenering/validation.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="attribut" type="xsd:string"></xsd:element>

	<xsd:element name="entite">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attribut" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="association" maxOccurs="unbounded" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>
		</xsd:complexType> 
	</xsd:element>
	<xsd:element name="association">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attribut" maxOccurs="unbounded" minOccurs="0"></xsd:element>
				<xsd:element ref="entite" maxOccurs="unbounded" minOccurs="0"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>
		</xsd:complexType> 
	</xsd:element>

	<xsd:element name="diagramme">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="entite" maxOccurs="unbounded" minOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType> 
	</xsd:element>
</xsd:schema>

=== juniordrizzy/Projet-SGBD-Reverse-Engeenering/diagramme.xml
<?xml version="1.0" encoding="UTF-8" ?>

<diagramme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="validation.xsd">
	<entite nom="Patient">
		<attribut>idPatient</attribut>
		<attribut>prenom</attribut>
		<attribut>nom</attribut>
		<attribut>adresse</attribut>
                <association nom="consomme">
	            <entite nom="Medicament">
		        <attribut>idMedicament</attribut>
		        <attribut>nom</attribut>
	                <association nom="prescrit">
	                    <entite nom="Medecin">
		                <attribut>idMedecin</attribut>
		                <attribut>prenom</attribut>
		                <attribut>nom</attribut>
		                <attribut>adresse</attribut>
    	                    </entite>
                       </association>
	           </entite>
               </association>
	   </entite>
</diagramme>
